[tools]
go = "1.24.2"
protoc = "latest"
buf = "latest"
just = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "latest"
